export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
export const AUTOLOGIN_SUCCESS = 'AUTOLOGIN_SUCCESS';
export const AUTOLOGIN_FAILURE = 'AUTOLOGIN_FAILURE';
